version: "3.8"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante-food-pedidos
    ports:
      - "3070:3306"
    volumes:
      - ./data:/var/lib/mysql

  flyway:
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:mariadb://db:3306/restaurante-food-pedidos -user=root -password=root migrate
    depends_on:
      - db
